# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=82)),
                ('url', models.URLField(max_length=400)),
                ('f_creacion', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=32)),
            ],
        ),
    ]
